title: Laura Steiner
description: Java developer, violist, violinist, teacher
titles_from_headings:
  enabled: false
author:
  name: Laura Steiner
  avatar: headshot-reduced.png
theme: jekyll-theme-tactile
